version: '3'

services:
  master:
    container_name: master
    restart: unless-stopped
    image: postgres:15.7
    ports:
      - "9001:5432"
    environment:
      - PGDATA=/var/lib/postgresql/data
      - PGENCODING=UTF8
      - PGLOCALE=en_US.UTF8
      - PGUSERNAME=postgres
      - POSTGRES_PASSWORD=postgres
    volumes:
      - /home/master/pg_data:/var/lib/postgresql/data
    networks:
      - brigada

  slave:
    container_name: slave
    restart: unless-stopped
    image: postgres:15.7
    ports:
      - "9002:5432"
    environment:
      - PGDATA=/var/lib/postgresql/data
      - PGENCODING=UTF8
      - PGLOCALE=en_US.UTF8
      - PGUSERNAME=postgres
      - POSTGRES_PASSWORD=postgres
    volumes:
      - /home/slave/pg_data:/var/lib/postgresql/data
    networks:
      - brigada

networks:
  brigada:
    driver: bridge
